trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - dev

variables:
  solution: 'Buttplug.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: NuGetToolInstaller@0
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NuGetToolInstaller@0
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          command: 'build'
          arguments: '--configuration ReleaseStandard -f netstandard2.0'
      # Turn off tests 'til I can figure out why nunit stalls
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'test'
      #     arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration ReleaseStandard -f netcoreapp2.1'
  - job: MacOS
    pool:
      vmImage: 'macos-10.13'
    steps:
      - task: NuGetToolInstaller@0
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration ReleaseStandard -f netstandard2.0'
      # Turn off tests 'til I can figure out why nunit stalls
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'test'
      #     arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration ReleaseStandard -f netcoreapp2.1'
