trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - dev

strategy:
  matrix:
    # linux:
    #   imageName: 'ubuntu-16.04'
    # mac:
    #   imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'      

pool:
  vmImage: $(imageName)

variables:
  solution: 'Buttplug.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
