trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - dev

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'      

pool:
  vmImage: $(imageName)

variables:
  solution: 'Buttplug.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@0

  # Get codecov, resharper, etc.
  # - powershell: choco install -y -r --no-progress resharper-clt.portable
  #   condition: eq( variables['Agent.OS'], 'Windows_NT' )
  #   displayName: Get Windows dependencies (resharper)
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: VSTest@2
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: DotNetCoreCLI@2
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      command: 'build'
      arguments: '--configuration ReleaseStandard -f netstandard2.0'
      
# Run Resharper
# Running it works, outputing warnings doesn't.
# - powershell: |
#     InspectCode.exe --output=resharper-clt-output.xml --project="Buttplug*" Buttplug.sln;
#     $result = [xml](Get-Content .\resharper-clt-output.xml)
#     $result.Report.Issues.ChildNodes | ForEach-Object {$project = $_.Name; $_.ChildNodes | ForEach-Object {Add-AppveyorCompilationMessage -Message $_.Message -Line $_.Line -FileName $_.File -ProjectName $project}}
#   condition: eq( variables['Agent.OS'], 'Windows_NT' )
#   displayName: Run resharper warnings


