trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - dev

variables:
  solution: 'Buttplug.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        displayName: "Build Project"
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: VSTest@2
        displayName: "Test Project"
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        displayName: "Build Project"
        inputs:
          command: 'build'
          arguments: '--configuration ReleaseStandard'
      # IPC Tests are turned off for this platform, as they time out.
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration ReleaseStandard'
  - job: MacOS
    pool:
      vmImage: 'macos-10.13'
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        displayName: "Build Project"
        inputs:
          command: 'build'
          arguments: '--configuration ReleaseStandard'
      # Timed tests on mac die constantly, just turn off mac tests for right now and trust we're covering windows/linux
      - task: DotNetCoreCLI@2
        condition: false
        displayName: "Test Project (Skipped due to timing issues on MacOS)"
        inputs:
          command: 'test'
          arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration ReleaseStandard'
