trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - dev

variables:
  solution: 'Buttplug.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: "Windows"
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Debug:
          buildConfiguration: Debug
        Release:
          buildConfiguration: Release
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        displayName: "Build Project"
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          maximumCpuCount: true
      - script: |
          cinst -y --no-progress opencover.portable nunit-console-runner codecov
          OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"Buttplug.Test\bin\$(buildConfiguration)\net47\Buttplug.Test.dll Buttplug.Client.Connectors.WebsocketConnector.Test\bin\$(buildConfiguration)\Buttplug.Client.Connectors.WebsocketConnector.Test.dll --inprocess --result=myresults.xml" -output:"coverage.xml" -excludebyfile:"*\*LibLog.cs" -filter:"+[*]* -[nunit*]*"
        displayName: 'Test with Code Coverage'
        condition: and(succeeded(), eq(variables['buildConfiguration'], 'Debug'))
      # Upload coverage to codecov.io
      - script: |
          codecov.exe -f "coverage.xml" -t $(CODECOV_TOKEN)
        displayName: Upload coverage to codecov.
        condition: and(succeeded(), eq(variables['buildConfiguration'], 'Debug'))
      - task: VSTest@2
        displayName: "Test Project"
        condition: and(succeeded(), eq(variables['buildConfiguration'], 'Release'))
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - powershell: |
          cinst -y docfx
          copy-item README.md docs\index.md
          copy-item *.md docs\articles\
          docfx docs\docfx.json
        displayName: Documentation Generation
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/dev')))
  - job: "Linux"
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Debug:
          buildConfiguration: Debug
        Release:
          buildConfiguration: Release
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        displayName: "Build Project"
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)Standard'
      # IPC Tests are turned off for this platform, as they time out.
      - task: DotNetCoreCLI@2
        displayName: "Test Project"
        inputs:
          command: 'test'
          arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration $(buildConfiguration)Standard'
  - job: "MacOS"
    pool:
      vmImage: 'macos-10.13'
    strategy:
      matrix:
        Debug:
          buildConfiguration: Debug
        Release:
          buildConfiguration: Release
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Install Platform Dependencies"
      - task: NuGetCommand@2
        displayName: "Restore Project"
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        displayName: "Build Project"
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)Standard'
      # Timed tests on mac die constantly, just turn off mac tests for right now and trust we're covering windows/linux
      - task: DotNetCoreCLI@2
        displayName: "Test Project"
        inputs:
          command: 'test'
          arguments: 'Buttplug.Test/Buttplug.Test.csproj --configuration $(buildConfiguration)Standard'
